FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
RUN apt-get update && apt-get install -y vim apt-utils libgdiplus libc6-dev tzdata
ENV TZ=Asia/Tehran
ENV DEBIAN_FRONTEND=noninteractive
ENV ASPNETCORE_ENVIRONMENT=Production
RUN mkdir -p /etc/keys
COPY ./bin/Release/netcoreapp3.1/publish	/publish
WORKDIR /publish
ENTRYPOINT ["dotnet", "TurbineJobMVC.dll"]